# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/agafonov/Documents/image_processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/agafonov/Documents/image_processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agafonov/Documents/image_processor/CMakeFiles /home/agafonov/Documents/image_processor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agafonov/Documents/image_processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image_processor

# Build rule for target.
image_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_processor
.PHONY : image_processor

# fast build rule for target.
image_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/build
.PHONY : image_processor/fast

bmpformat.o: bmpformat.cpp.o
.PHONY : bmpformat.o

# target to build an object file
bmpformat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpformat.cpp.o
.PHONY : bmpformat.cpp.o

bmpformat.i: bmpformat.cpp.i
.PHONY : bmpformat.i

# target to preprocess a source file
bmpformat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpformat.cpp.i
.PHONY : bmpformat.cpp.i

bmpformat.s: bmpformat.cpp.s
.PHONY : bmpformat.s

# target to generate assembly for a file
bmpformat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpformat.cpp.s
.PHONY : bmpformat.cpp.s

bmpreader.o: bmpreader.cpp.o
.PHONY : bmpreader.o

# target to build an object file
bmpreader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpreader.cpp.o
.PHONY : bmpreader.cpp.o

bmpreader.i: bmpreader.cpp.i
.PHONY : bmpreader.i

# target to preprocess a source file
bmpreader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpreader.cpp.i
.PHONY : bmpreader.cpp.i

bmpreader.s: bmpreader.cpp.s
.PHONY : bmpreader.s

# target to generate assembly for a file
bmpreader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpreader.cpp.s
.PHONY : bmpreader.cpp.s

bmpwriter.o: bmpwriter.cpp.o
.PHONY : bmpwriter.o

# target to build an object file
bmpwriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpwriter.cpp.o
.PHONY : bmpwriter.cpp.o

bmpwriter.i: bmpwriter.cpp.i
.PHONY : bmpwriter.i

# target to preprocess a source file
bmpwriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpwriter.cpp.i
.PHONY : bmpwriter.cpp.i

bmpwriter.s: bmpwriter.cpp.s
.PHONY : bmpwriter.s

# target to generate assembly for a file
bmpwriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/bmpwriter.cpp.s
.PHONY : bmpwriter.cpp.s

color.o: color.cpp.o
.PHONY : color.o

# target to build an object file
color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/color.cpp.o
.PHONY : color.cpp.o

color.i: color.cpp.i
.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s
.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/color.cpp.s
.PHONY : color.cpp.s

consoleoutput.o: consoleoutput.cpp.o
.PHONY : consoleoutput.o

# target to build an object file
consoleoutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/consoleoutput.cpp.o
.PHONY : consoleoutput.cpp.o

consoleoutput.i: consoleoutput.cpp.i
.PHONY : consoleoutput.i

# target to preprocess a source file
consoleoutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/consoleoutput.cpp.i
.PHONY : consoleoutput.cpp.i

consoleoutput.s: consoleoutput.cpp.s
.PHONY : consoleoutput.s

# target to generate assembly for a file
consoleoutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/consoleoutput.cpp.s
.PHONY : consoleoutput.cpp.s

filter.o: filter.cpp.o
.PHONY : filter.o

# target to build an object file
filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filter.cpp.o
.PHONY : filter.cpp.o

filter.i: filter.cpp.i
.PHONY : filter.i

# target to preprocess a source file
filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filter.cpp.i
.PHONY : filter.cpp.i

filter.s: filter.cpp.s
.PHONY : filter.s

# target to generate assembly for a file
filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filter.cpp.s
.PHONY : filter.cpp.s

filtercrop.o: filtercrop.cpp.o
.PHONY : filtercrop.o

# target to build an object file
filtercrop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtercrop.cpp.o
.PHONY : filtercrop.cpp.o

filtercrop.i: filtercrop.cpp.i
.PHONY : filtercrop.i

# target to preprocess a source file
filtercrop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtercrop.cpp.i
.PHONY : filtercrop.cpp.i

filtercrop.s: filtercrop.cpp.s
.PHONY : filtercrop.s

# target to generate assembly for a file
filtercrop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtercrop.cpp.s
.PHONY : filtercrop.cpp.s

filteredgedetection.o: filteredgedetection.cpp.o
.PHONY : filteredgedetection.o

# target to build an object file
filteredgedetection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filteredgedetection.cpp.o
.PHONY : filteredgedetection.cpp.o

filteredgedetection.i: filteredgedetection.cpp.i
.PHONY : filteredgedetection.i

# target to preprocess a source file
filteredgedetection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filteredgedetection.cpp.i
.PHONY : filteredgedetection.cpp.i

filteredgedetection.s: filteredgedetection.cpp.s
.PHONY : filteredgedetection.s

# target to generate assembly for a file
filteredgedetection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filteredgedetection.cpp.s
.PHONY : filteredgedetection.cpp.s

filtergaussianblur.o: filtergaussianblur.cpp.o
.PHONY : filtergaussianblur.o

# target to build an object file
filtergaussianblur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtergaussianblur.cpp.o
.PHONY : filtergaussianblur.cpp.o

filtergaussianblur.i: filtergaussianblur.cpp.i
.PHONY : filtergaussianblur.i

# target to preprocess a source file
filtergaussianblur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtergaussianblur.cpp.i
.PHONY : filtergaussianblur.cpp.i

filtergaussianblur.s: filtergaussianblur.cpp.s
.PHONY : filtergaussianblur.s

# target to generate assembly for a file
filtergaussianblur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtergaussianblur.cpp.s
.PHONY : filtergaussianblur.cpp.s

filtergrayscale.o: filtergrayscale.cpp.o
.PHONY : filtergrayscale.o

# target to build an object file
filtergrayscale.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtergrayscale.cpp.o
.PHONY : filtergrayscale.cpp.o

filtergrayscale.i: filtergrayscale.cpp.i
.PHONY : filtergrayscale.i

# target to preprocess a source file
filtergrayscale.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtergrayscale.cpp.i
.PHONY : filtergrayscale.cpp.i

filtergrayscale.s: filtergrayscale.cpp.s
.PHONY : filtergrayscale.s

# target to generate assembly for a file
filtergrayscale.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtergrayscale.cpp.s
.PHONY : filtergrayscale.cpp.s

filternegative.o: filternegative.cpp.o
.PHONY : filternegative.o

# target to build an object file
filternegative.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filternegative.cpp.o
.PHONY : filternegative.cpp.o

filternegative.i: filternegative.cpp.i
.PHONY : filternegative.i

# target to preprocess a source file
filternegative.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filternegative.cpp.i
.PHONY : filternegative.cpp.i

filternegative.s: filternegative.cpp.s
.PHONY : filternegative.s

# target to generate assembly for a file
filternegative.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filternegative.cpp.s
.PHONY : filternegative.cpp.s

filtersharpening.o: filtersharpening.cpp.o
.PHONY : filtersharpening.o

# target to build an object file
filtersharpening.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtersharpening.cpp.o
.PHONY : filtersharpening.cpp.o

filtersharpening.i: filtersharpening.cpp.i
.PHONY : filtersharpening.i

# target to preprocess a source file
filtersharpening.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtersharpening.cpp.i
.PHONY : filtersharpening.cpp.i

filtersharpening.s: filtersharpening.cpp.s
.PHONY : filtersharpening.s

# target to generate assembly for a file
filtersharpening.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filtersharpening.cpp.s
.PHONY : filtersharpening.cpp.s

image.o: image.cpp.o
.PHONY : image.o

# target to build an object file
image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image.cpp.o
.PHONY : image.cpp.o

image.i: image.cpp.i
.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s
.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image.cpp.s
.PHONY : image.cpp.s

image_processor.o: image_processor.cpp.o
.PHONY : image_processor.o

# target to build an object file
image_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.cpp.o
.PHONY : image_processor.cpp.o

image_processor.i: image_processor.cpp.i
.PHONY : image_processor.i

# target to preprocess a source file
image_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.cpp.i
.PHONY : image_processor.cpp.i

image_processor.s: image_processor.cpp.s
.PHONY : image_processor.s

# target to generate assembly for a file
image_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.cpp.s
.PHONY : image_processor.cpp.s

matrixfilter.o: matrixfilter.cpp.o
.PHONY : matrixfilter.o

# target to build an object file
matrixfilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/matrixfilter.cpp.o
.PHONY : matrixfilter.cpp.o

matrixfilter.i: matrixfilter.cpp.i
.PHONY : matrixfilter.i

# target to preprocess a source file
matrixfilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/matrixfilter.cpp.i
.PHONY : matrixfilter.cpp.i

matrixfilter.s: matrixfilter.cpp.s
.PHONY : matrixfilter.s

# target to generate assembly for a file
matrixfilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/matrixfilter.cpp.s
.PHONY : matrixfilter.cpp.s

parserargv.o: parserargv.cpp.o
.PHONY : parserargv.o

# target to build an object file
parserargv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/parserargv.cpp.o
.PHONY : parserargv.cpp.o

parserargv.i: parserargv.cpp.i
.PHONY : parserargv.i

# target to preprocess a source file
parserargv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/parserargv.cpp.i
.PHONY : parserargv.cpp.i

parserargv.s: parserargv.cpp.s
.PHONY : parserargv.s

# target to generate assembly for a file
parserargv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/parserargv.cpp.s
.PHONY : parserargv.cpp.s

pixelfilter.o: pixelfilter.cpp.o
.PHONY : pixelfilter.o

# target to build an object file
pixelfilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/pixelfilter.cpp.o
.PHONY : pixelfilter.cpp.o

pixelfilter.i: pixelfilter.cpp.i
.PHONY : pixelfilter.i

# target to preprocess a source file
pixelfilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/pixelfilter.cpp.i
.PHONY : pixelfilter.cpp.i

pixelfilter.s: pixelfilter.cpp.s
.PHONY : pixelfilter.s

# target to generate assembly for a file
pixelfilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/pixelfilter.cpp.s
.PHONY : pixelfilter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_processor"
	@echo "... bmpformat.o"
	@echo "... bmpformat.i"
	@echo "... bmpformat.s"
	@echo "... bmpreader.o"
	@echo "... bmpreader.i"
	@echo "... bmpreader.s"
	@echo "... bmpwriter.o"
	@echo "... bmpwriter.i"
	@echo "... bmpwriter.s"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... consoleoutput.o"
	@echo "... consoleoutput.i"
	@echo "... consoleoutput.s"
	@echo "... filter.o"
	@echo "... filter.i"
	@echo "... filter.s"
	@echo "... filtercrop.o"
	@echo "... filtercrop.i"
	@echo "... filtercrop.s"
	@echo "... filteredgedetection.o"
	@echo "... filteredgedetection.i"
	@echo "... filteredgedetection.s"
	@echo "... filtergaussianblur.o"
	@echo "... filtergaussianblur.i"
	@echo "... filtergaussianblur.s"
	@echo "... filtergrayscale.o"
	@echo "... filtergrayscale.i"
	@echo "... filtergrayscale.s"
	@echo "... filternegative.o"
	@echo "... filternegative.i"
	@echo "... filternegative.s"
	@echo "... filtersharpening.o"
	@echo "... filtersharpening.i"
	@echo "... filtersharpening.s"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
	@echo "... image_processor.o"
	@echo "... image_processor.i"
	@echo "... image_processor.s"
	@echo "... matrixfilter.o"
	@echo "... matrixfilter.i"
	@echo "... matrixfilter.s"
	@echo "... parserargv.o"
	@echo "... parserargv.i"
	@echo "... parserargv.s"
	@echo "... pixelfilter.o"
	@echo "... pixelfilter.i"
	@echo "... pixelfilter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

